import { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';

import InterestTag from '../../components/atoms/InterestTag.jsx';
import EmailDigestWidget from '../../components/widgets/EmailDigestWidget.jsx';
import LegendWidget from '../../components/widgets/LegendWidget.jsx';
import QuickLinksWidget from '../../components/widgets/QuickLinksWidget.jsx';
import SimilarResearchersWidget from '../../components/widgets/SimilarResearchersWidget.jsx';
import WeekStatsWidget from '../../components/widgets/WeekStatsWidget.jsx';
import Widget from '../../components/widgets/Widget.jsx';

import FeedHeader from './FeedHeader.jsx';
import FeedPaperCard from './FeedPaperCard.jsx';
import useRecommendations from './useRecommendations.js';
import { quickLinks, similarResearchers, weekStats } from './mockData.js';
import useInterests from '../profile/useInterests.js';
import useProfile from '../profile/useProfile.js';
import useSavedPapers from '../reading-list/useSavedPapers.js';
import useFeedback from './useFeedback.js';
import { isMockMode } from '../../lib/api.js';
import styles from './FeedPage.module.css';

const DEFAULT_PAGE_SIZE = 10;
const PAGE_SIZE_OPTIONS = [5, 10, 20, 50];


// Helper function generated by Codex in the process of implementing pagination -- AI usage report is reported in the main component below.
function getPageItems(currentPage, totalPages) {
  if (totalPages <= 7) {
    return Array.from({ length: totalPages }, (_, index) => index + 1);
  }

  if (currentPage <= 4) {
    return [1, 2, 3, 4, 5, 'end-ellipsis', totalPages];
  }

  if (currentPage >= totalPages - 3) {
    return [
      1,
      'start-ellipsis',
      totalPages - 4,
      totalPages - 3,
      totalPages - 2,
      totalPages - 1,
      totalPages,
    ];
  }

  const items = [1];
  const start = Math.max(2, currentPage - 1);
  const end = Math.min(totalPages - 1, currentPage + 1);

  if (start > 2) {
    items.push('start-ellipsis');
  }

  for (let page = start; page <= end; page += 1) {
    items.push(page);
  }

  if (end < totalPages - 1) {
    items.push('end-ellipsis');
  }

  items.push(totalPages);
  return items;
}

export default function FeedPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const searchQuery = location.state?.searchQuery || '';

  const { status: profileStatus } = useProfile();
  const { status, batch, recommendations, error } = useRecommendations({
    enabled: profileStatus !== 'loading' && profileStatus !== 'no-profile',
  });
  const { interests } = useInterests();
  const { savedPapers } = useSavedPapers();
  const savedPaperIds = new Set(savedPapers.map((p) => p.id));
  const { voteByPaperId } = useFeedback();

  // [GenAI Usage] Prompt: Add client-side search filtering to the feed that checks the
  // search query (passed via router state) against paper titles, authors, and abstracts.
  // The filter needs to handle the nested data structure where paper data lives inside
  // rec.paper (not directly on rec). Initially Claude got the field names wrong because
  // it assumed flat structure, so I had to debug by looking at FeedPaperCard to see the
  // actual shape (rec.paper.title, rec.paper.authors_text, rec.paper.abstract). The
  // filtering should be case-insensitive and match partial strings.
  // [GenAI Usage] LLM response begins:
  const filteredRecommendations = searchQuery
    ? recommendations.filter((rec) => {
        const searchLower = searchQuery.toLowerCase();
        const paper = rec.paper || {};
        const titleMatch = paper.title?.toLowerCase().includes(searchLower);
        const authorsMatch = paper.authors_text?.toLowerCase().includes(searchLower);
        const abstractMatch = paper.abstract?.toLowerCase().includes(searchLower);
        return titleMatch || authorsMatch || abstractMatch;
      })
    : recommendations;
  // [GenAI Usage] LLM response ends
  // [GenAI Reflection] I tested the initial implementation and got 0 results for every
  // query, which led me to realize the data structure assumption was wrong. After checking
  // how FeedPaperCard accesses the data, I corrected the field paths and verified the
  // filtering works across all three fields (title, authors, abstract).

  // Dont delete comments below
  // [GenAI Usage] Prompt: add client-side pagination to the feed — show PAGE_SIZE papers at a time,
  // wire the existing "Load more" button to reveal the next page, and reset when a new batch loads.
  // [GenAI Usage] Response begins:
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const totalPages = Math.max(1, Math.ceil(filteredRecommendations.length / pageSize));
  const currentPageSafe = Math.min(currentPage, totalPages);
  const pageStart = (currentPageSafe - 1) * pageSize;
  const pageEnd = pageStart + pageSize;
  const visibleRecommendations = filteredRecommendations.slice(pageStart, pageEnd);
  const pageItems = getPageItems(currentPageSafe, totalPages);

  // Reset pagination when a new batch loads.
  useEffect(() => {
    setCurrentPage(1);
  }, [batch?.id]);

  useEffect(() => {
    if (currentPage > totalPages) {
      setCurrentPage(totalPages);
    }
  }, [currentPage, totalPages]);
  // [GenAI Usage] Response ends

  return (
    <div>
      <h2 className="sr-only">
        Paper Aggregator — personalized research feed dashboard
      </h2>

      <div className={styles.body}>
        {/* LEFT SIDEBAR ------------------------------------------------------ */}
        <aside className={styles.sidebar}>
          <Widget title="Research Interests">
            <div>
              {interests.length === 0 ? (
                <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)' }}>
                  No interests yet. Add some on your profile.
                </div>
              ) : (
                interests.map((i) => (
                  <InterestTag key={i.id} kind={i.interest_type}>
                    {i.value}
                  </InterestTag>
                ))
              )}
            </div>
            <button
              type="button"
              className={styles.addBtn}
              onClick={() => navigate('/profile?tab=interests')}
            >
              + Add interest
            </button>
          </Widget>

          <LegendWidget />
          {isMockMode() ? (
            <EmailDigestWidget />
          ) : (
            <Widget title="Email Digest">
              <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', padding: '4px 0' }}>
                Coming soon.
              </div>
            </Widget>
          )}
        </aside>

        {/* FEED ------------------------------------------------------------- */}
        <main className={styles.feed}>
          {searchQuery && (
            <div style={{
              padding: '10px 16px',
              marginBottom: '12px',
              background: 'var(--color-background-secondary)',
              borderRadius: 'var(--border-radius-md)',
              fontSize: '13px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <span>
                Searching for: <strong>{searchQuery}</strong> ({filteredRecommendations.length} results)
              </span>
              <button
                type="button"
                onClick={() => navigate('/feed', { replace: true })}
                style={{
                  padding: '4px 10px',
                  fontSize: '12px',
                  border: '0.5px solid var(--color-border-tertiary)',
                  borderRadius: 'var(--border-radius-md)',
                  background: 'var(--color-background-primary)',
                  cursor: 'pointer',
                }}
              >
                Clear search
              </button>
            </div>
          )}
          <FeedHeader batch={batch} count={filteredRecommendations.length} />

          {profileStatus === 'no-profile' ? (
            <div className={styles.status}>
              Complete your profile to get personalized recommendations.{' '}
              <button
                type="button"
                className={styles.addBtn}
                onClick={() => navigate('/profile?tab=edit')}
              >
                Set up profile →
              </button>
            </div>
          ) : null}

          {status === 'loading' ? (
            <div className={styles.status}>Loading recommendations…</div>
          ) : null}

          {status === 'no-token' ? (
            <div className={styles.status}>{error}</div>
          ) : null}

          {status === 'network-error' ? (
            <div className={styles.status}>
              {error} Start it with{' '}
              <code>cd backend && uvicorn app.main:app --reload</code>.
            </div>
          ) : null}

          {status === 'unauthorized' ? (
            <div className={styles.status}>
              Your session expired or the backend rejected the token. Try
              signing out and back in.
            </div>
          ) : null}

          {status === 'error' ? (
            <div className={styles.status}>
              Could not load recommendations: {error}
            </div>
          ) : null}

          {status === 'ready' && recommendations.length === 0 ? (
            <div className={styles.status}>
              {interests.length === 0 ? (
                <>
                  Add research interests to your profile to get personalized recommendations.{' '}
                  <button
                    type="button"
                    className={styles.addBtn}
                    onClick={() => navigate('/profile?tab=interests')}
                  >
                    Add interests →
                  </button>
                </>
              ) : (
                'No recommendations yet — reload to generate your first batch.'
              )}
            </div>
          ) : null}

          {/* [GenAI Usage] Response begins (pagination render) */}
          {visibleRecommendations.map((rec, idx) => (
            <FeedPaperCard
              key={rec.id}
              rec={{
                ...rec,
                user_saved: savedPaperIds.has(rec.paper_id),
                user_vote: voteByPaperId.get(rec.paper_id) ?? 0,
              }}
              unread={pageStart + idx < 2}
            />
          ))}

          {/* Dont delete all comments below: GenAI Usage 2: [Codex prompt] 
          can you change the display of the pagination feature in the frontend right now under Today's feed. the problem that i see is that
  it only has one button. I need to have pages like 1, 2, 3, 4 ... and then i need to allow the user to choose between how many pages
  they want to display per page. Default shall be 10. Also you need to make sure this pagination UI section only span one line.
  */}
  {/* GenAI Usage: LLM responses begins: */}
          {status === 'ready' && recommendations.length > 0 ? (
            <div className={styles.pagination} aria-label="Feed pagination">
              <div className={styles.pageSizeControl}>
                <label htmlFor="feed-page-size">Papers per page</label>
                <select
                  id="feed-page-size"
                  value={pageSize}
                  onChange={(event) => {
                    setPageSize(Number(event.target.value));
                    setCurrentPage(1);
                  }}
                >
                  {PAGE_SIZE_OPTIONS.map((option) => (
                    <option key={option} value={option}>
                      {option}
                    </option>
                  ))}
                </select>
              </div>

              {totalPages > 1 ? (
                <div className={styles.pageButtons}>
                  <button
                    type="button"
                    className={styles.pageButton}
                    onClick={() => setCurrentPage((page) => Math.max(1, page - 1))}
                    disabled={currentPageSafe === 1}
                    aria-label="Previous page"
                  >
                    Prev
                  </button>

                  {pageItems.map((item) =>
                    typeof item === 'number' ? (
                      <button
                        type="button"
                        key={item}
                        className={`${styles.pageButton} ${
                          item === currentPageSafe ? styles.pageButtonActive : ''
                        }`}
                        onClick={() => setCurrentPage(item)}
                        aria-current={item === currentPageSafe ? 'page' : undefined}
                      >
                        {item}
                      </button>
                    ) : (
                      <span key={item} className={styles.pageEllipsis} aria-hidden="true">
                        ...
                      </span>
                    ),
                  )}

                  <button
                    type="button"
                    className={styles.pageButton}
                    onClick={() =>
                      setCurrentPage((page) => Math.min(totalPages, page + 1))
                    }
                    disabled={currentPageSafe === totalPages}
                    aria-label="Next page"
                  >
                    Next
                  </button>
                </div>
              ) : null}

              <div className={styles.pageSummary}>
                Showing {pageStart + 1}-{Math.min(pageEnd, recommendations.length)} of{' '}
                {recommendations.length}
              </div>
            </div>
          ) : null}
          {/* Dont delete all comments below: GenAI Usage: LLM response ends */}
          {/* [GenAI Usage 2] Response ends */}
          {/* GenAI Reflection */}
          {/* In this code, I describe clearly the pagination feature to Codex with clear goals -- one-line section, default behavior, pagination overlook. 
            When these features described, pagination shall be implemented easily by Codex because it is a well-defined task. Indeed, after inpsect the code carefully and thoroughly, 
            Codex wrote acceptable code. I also verified the result in the browser and confirmed it just works as expected. */}
          {/* [GenAI Reflection] The pagination logic is straightforward — visibleCount slices the
              already-loaded recommendations array, and the useEffect reset on batch?.id ensures the
              page resets when fresh recommendations arrive. I verified the button hides correctly
              when all papers are visible. */}
        </main>

        {/* RIGHT SIDEBAR ---------------------------------------------------- */}
        <aside className={styles.right}>
          {isMockMode() ? (
            <>
              <WeekStatsWidget stats={weekStats} />
              <SimilarResearchersWidget researchers={similarResearchers} />
              <QuickLinksWidget links={quickLinks} />
            </>
          ) : (
            <>
              <Widget title="This Week">
                <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', padding: '4px 0' }}>
                  Coming soon.
                </div>
              </Widget>
              <Widget title="Similar Researchers">
                <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', padding: '4px 0' }}>
                  Coming soon.
                </div>
              </Widget>
              <Widget title="Quick Links">
                <div style={{ fontSize: 12, color: 'var(--color-text-tertiary)', padding: '4px 0' }}>
                  Coming soon.
                </div>
              </Widget>
            </>
          )}
        </aside>
      </div>
    </div>
  );
}
